#!/usr/bin/env node
/**
 * FRAMEGEN — Interactive setup wizard
 * Run: node scripts/setup.js
 */

import { createInterface } from "readline";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = join(__dirname, "..");

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask  = (q)      => new Promise(res => rl.question(q, res));
const log  = (s = "") => console.log(s);
const dim  = s        => `\x1b[2m${s}\x1b[0m`;
const bold = s        => `\x1b[1m${s}\x1b[0m`;
const cyan = s        => `\x1b[36m${s}\x1b[0m`;
const green= s        => `\x1b[32m${s}\x1b[0m`;
const warn = s        => `\x1b[33m${s}\x1b[0m`;

log();
log(bold(cyan("  ██████╗ ██████╗  █████╗ ███╗   ███╗███████╗")));
log(bold(cyan("  ██╔════╝ ██╔══██╗██╔══██╗████╗ ████║██╔════╝")));
log(bold(cyan("  █████╗   ██████╔╝███████║██╔████╔██║█████╗  ")));
log(bold(cyan("  ██╔══╝   ██╔══██╗██╔══██║██║╚██╔╝██║██╔══╝  ")));
log(bold(cyan("  ██║      ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗")));
log(bold(cyan("  ╚═╝      ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝")));
log();
log(bold("  Chat → Blueprint → Video  |  Personal AI video tool"));
log(dim("  Open-source models via Replicate · Local pipeline · FFmpeg stitch"));
log();
log("  ─────────────────────────────────────────────────────────");
log();

// Check existing .env
let existing = {};
const envPath = join(ROOT, ".env");
if (existsSync(envPath)) {
  const lines = readFileSync(envPath, "utf8").split("\n");
  for (const line of lines) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) existing[m[1]] = m[2];
  }
  log(warn("  Found existing .env — values will be shown as [CONFIGURED]"));
  log();
}

// ── Anthropic key ──────────────────────────────────────────
log(bold("  Step 1: Anthropic API Key (required)"));
log(dim("  Used for: Claude chat → blueprint generation"));
log(dim("  Get it at: https://console.anthropic.com/settings/api-keys"));
log();
let anthropicKey = existing.ANTHROPIC_API_KEY || "";
if (anthropicKey) {
  log(green("  [CONFIGURED] ANTHROPIC_API_KEY is already set."));
  const change = await ask("  Change it? (y/N) ");
  if (change.toLowerCase() === "y") {
    anthropicKey = await ask("  Paste your Anthropic API key: ");
  }
} else {
  anthropicKey = await ask("  Paste your Anthropic API key: ");
}
log();

// ── Replicate key ──────────────────────────────────────────
log(bold("  Step 2: Replicate API Key (required for video generation)"));
log(dim("  Used for: Wan 2.1, Wan 2.2 Fast, LTX-Video (all open-source)"));
log(dim("  Get it at: https://replicate.com/account/api-tokens"));
log(dim("  Free trial credits included on sign-up. ~$0.04–0.08 per 5s clip."));
log();
let replicateKey = existing.REPLICATE_API_KEY || "";
if (replicateKey) {
  log(green("  [CONFIGURED] REPLICATE_API_KEY is already set."));
  const change = await ask("  Change it? (y/N) ");
  if (change.toLowerCase() === "y") {
    replicateKey = await ask("  Paste your Replicate API key: ");
  }
} else {
  replicateKey = await ask("  Paste your Replicate API key (or press Enter to skip): ");
}
log();

// ── FAL.ai key (optional) ──────────────────────────────────
log(bold("  Step 3: FAL.ai Key (optional fallback)"));
log(dim("  Fallback video provider. Skip if using Replicate."));
let falKey = existing.FAL_API_KEY || "";
if (falKey) {
  log(green("  [CONFIGURED] FAL_API_KEY is already set."));
} else {
  falKey = await ask("  Paste FAL.ai key (or press Enter to skip): ");
}
log();

// ── Write .env ──────────────────────────────────────────────
const env = `# FRAMEGEN — Environment Config
# Generated by setup wizard

# Anthropic (required for blueprint generation)
ANTHROPIC_API_KEY=${anthropicKey}

# Replicate — open-source video models (recommended)
# Models: wavespeedai/wan-2.1-t2v-480p, wan-video/wan-2.2-t2v-fast, lightricks/ltx-video
REPLICATE_API_KEY=${replicateKey}

# FAL.ai — fallback video provider (optional)
FAL_API_KEY=${falKey}

# Server
PORT=3002
CLIENT_URL=http://localhost:5174
NODE_ENV=development
`;

writeFileSync(envPath, env);
log(green("  ✓ .env written successfully"));
log();

// ── Install deps ────────────────────────────────────────────
log(bold("  Step 4: Installing dependencies…"));
log();
try {
  execSync("npm install", { cwd: ROOT, stdio: "inherit" });
  log();
  execSync("npm install", { cwd: join(ROOT, "client"), stdio: "inherit" });
  log();
  log(green("  ✓ Dependencies installed"));
} catch (e) {
  log(warn("  ✗ npm install failed — try running 'npm run install:all' manually"));
}
log();

// ── Check ffmpeg ────────────────────────────────────────────
try {
  execSync("which ffmpeg", { stdio: "ignore" });
  log(green("  ✓ FFmpeg detected"));
} catch {
  log(warn("  ⚠ FFmpeg not found — scene stitching won't work"));
  log(dim("    macOS:  brew install ffmpeg"));
  log(dim("    Ubuntu: sudo apt install ffmpeg"));
  log(dim("    Windows: https://ffmpeg.org/download.html"));
}
log();

// ── Summary ─────────────────────────────────────────────────
log("  ─────────────────────────────────────────────────────────");
log();
log(bold("  Setup complete! To start:"));
log();
log(cyan("    npm run dev"));
log();
log(dim("  Then open: http://localhost:5174"));
log();
if (!replicateKey && !falKey) {
  log(warn("  ⚠ No video API key configured."));
  log(warn("    Blueprint generation will work but video generation will fail."));
  log(warn("    Add REPLICATE_API_KEY to .env to enable video generation."));
  log();
}
log("  ─────────────────────────────────────────────────────────");
log();

rl.close();
